version: '3.7'

services:
    app:
        build: .
        volumes:
            - ./app:/usr/src/app
        ports:
            - 8501:8501
        restart: always
        command: streamlit run main.py --server.port 8501